blank_issues_enabled: false
contact_links:
    - name: â¤´ï¸ Upgrade Issue or Installation issue
      url: https://pub.dev/packages/razorpay_flutter
      about: Need help upgrading to the latest flutter version? Follow steps from our plugin docuemntation.
    - name: ğŸ¤” Need some help in Integrations
      url: https://razorpay.com/integrations/
      about: Looking for help with your app? Please refer to the integration documentation.
    - name: ğŸš€ Discussions and Proposals
      about: We are working on this, for now you can raise an issue and tell us what you think âœŒğŸ».
